# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe8ba6d3f65ec58c53935811e1205f6c9d45a9fe914c7b8d06aea37877c39d2f41de3f810cd15f7062cf89d5b866302e1aeda674a97fdd5606e7ef48b7e0e6d

test:
  secret_key_base: dd62d77d8267cc761b3bfde7c3f7180be9f8e26f556dd70a62ac6c488384e302a4b385fc0ba5a9be0c0d1b06b265d9aa4d6521d8c85a3ffe93d7b84cd9cace05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
